import '../core/constants/api_constants.dart';
import '../core/exceptions/app_exceptions.dart';
import '../core/network/api_client.dart';
import '../models/allocation.dart';
import '../models/financial_ledger.dart';
import '../models/purchase_order.dart';
import '../models/resource.dart';

/// Service managing hospital resources, equipment scan reservations, and financial logs.
class ResourceService {
  final ApiClient _client;

  ResourceService({ApiClient? client}) : _client = client ?? ApiClient();

  /// Fetches complete resource status, allocations, financials, and purchasing info.
  Future<Map<String, dynamic>> getHospitalData() async {
    try {
      final response = await _client.get(ApiConstants.data);
      final results = response['d']?['results'] as Map<String, dynamic>? ?? {};
      return results;
    } on AppException {
      rethrow;
    } catch (e) {
      throw ApiException(message: 'Failed to retrieve hospital data: ${e.toString()}');
    }
  }

  /// Fetches the hospital resource counts (beds, blood, equipment).
  Future<HospitalResource> getResources() async {
    final data = await getHospitalData();
    final resourcesJson = data['hms_resources'] as Map<String, dynamic>? ?? {};
    return HospitalResource.fromJson(resourcesJson);
  }

  /// Fetches all resource allocations.
  Future<List<Allocation>> getAllocations() async {
    final data = await getHospitalData();
    final rawList = data['hms_allocations'] as List<dynamic>? ?? [];
    return rawList
        .whereType<Map<String, dynamic>>()
        .map((json) => Allocation.fromJson(json))
        .toList();
  }

  /// Fetches financial ledger entries (charges, fees, bills).
  Future<List<FinancialLedger>> getFinancialLedgers() async {
    final data = await getHospitalData();
    final rawList = data['hms_financials'] as List<dynamic>? ?? [];
    return rawList
        .whereType<Map<String, dynamic>>()
        .map((json) => FinancialLedger.fromJson(json))
        .toList();
  }

  /// Fetches purchase orders generated by resource safety triggers.
  Future<List<PurchaseOrder>> getPurchaseOrders() async {
    final data = await getHospitalData();
    final rawList = data['hms_purchasing'] as List<dynamic>? ?? [];
    return rawList
        .whereType<Map<String, dynamic>>()
        .map((json) => PurchaseOrder.fromJson(json))
        .toList();
  }

  /// Books a diagnostic scan (MRI, CT-Scan, X-Ray, Ventilator) via POST /api/scans.
  Future<Allocation> bookScan({
    required String patientId,
    required String equipment,
    required String date,
    required String slot,
  }) async {
    try {
      final response = await _client.post(
        ApiConstants.scans,
        body: {
          'patientId': patientId,
          'equipment': equipment,
          'date': date,
          'slot': slot,
        },
      );

      final scanJson = response['scan'] as Map<String, dynamic>?;
      if (scanJson == null) {
        throw const ApiException(message: 'Failed to schedule scan allocation.');
      }

      return Allocation.fromJson(scanJson);
    } on AppException {
      rethrow;
    } catch (e) {
      throw ApiException(message: 'Failed to schedule scan: ${e.toString()}');
    }
  }

  /// Admin endpoint to overwrite hospital resource totals via PUT /api/resources.
  Future<HospitalResource> updateResources(HospitalResource resource) async {
    try {
      final response = await _client.put(
        ApiConstants.resources,
        body: {'resources': resource.toJson()},
      );

      final resJson = response['resources'] as Map<String, dynamic>?;
      if (resJson == null) {
        throw const ApiException(message: 'Failed to update resource levels.');
      }

      return HospitalResource.fromJson(resJson);
    } on AppException {
      rethrow;
    } catch (e) {
      throw ApiException(message: 'Update failed: ${e.toString()}');
    }
  }
}
